// arranger.ts — auto-evolving beat development. Every `sectionBars` cycles regenerates the
// 9 lane patterns (8 drums + bass) and global feel; a 1→5 stage arc controls intensity. The
// patterns are generated by COMBINING factors (climate / current / soil / weather) through an
// ENGINE (plant growth / physics oscillation / geometry quantisation), then flavoured by the
// GENRE character (jazz swing / dub space / minimal tightness / dubstep halftime / noise).
import type { ParamState } from "../core/params";
import type { BeatSequencer } from "./beat";

export const ENGINES = ["PLANT", "PHYSICS", "GEOMETRY"] as const;
export const CLIMATES = ["tropical", "temperate", "arid", "polar"] as const;
export const CURRENTS = ["warm", "cold", "gyre", "upwelling"] as const;
export const SOILS = ["sand", "clay", "loam", "volcanic"] as const;
export const WEATHERS = ["clear", "rain", "storm", "fog"] as const;

const CLIMATE_V: Record<string, number> = { tropical: 0.9, temperate: 0.55, arid: 0.4, polar: 0.15 };
const CURRENT_V: Record<string, number> = { warm: 0.7, cold: 0.3, gyre: 0.5, upwelling: 0.85 };
const SOIL_V: Record<string, number> = { sand: 0.3, clay: 0.6, loam: 0.78, volcanic: 0.92 };
const WEATHER_V: Record<string, number> = { clear: 0.4, rain: 0.6, storm: 0.9, fog: 0.25 };
const STAGE_E = [0, 0.2, 0.45, 0.7, 1.0, 0.4];

// lanes: kick0 snare1 clap2 hat3 ohat4 tom5 rim6 perc7 bass8
const K = 0, SN = 1, CL = 2, HAT = 3, OH = 4, TOM = 5, RIM = 6, PERC = 7, BASS = 8;
const BASE = [0.25, 0.18, 0.12, 0.5, 0.2, 0.12, 0.2, 0.3, 0.4];

interface GC {
  swing: number; sidechain: number; reverb: number; hatMul: number; densityMul: number;
  kick: "sparse" | "floor" | "dubfloor" | "half" | "euclid";
  snare: "comp" | "backbeat" | "half" | "euclid";
  bass: "walk" | "sparse" | "eighths" | "sync" | "dense";
}
const GENRE: Record<string, GC> = {
  JAZZ:    { swing: 0.55, sidechain: 0.2, reverb: 0.12, hatMul: 1.4, densityMul: 0.9, kick: "sparse", snare: "comp", bass: "walk" },
  DUB:     { swing: 0.3,  sidechain: 0.5, reverb: 0.38, hatMul: 0.6, densityMul: 0.55, kick: "dubfloor", snare: "backbeat", bass: "sparse" },
  MINIMAL: { swing: 0.15, sidechain: 0.4, reverb: 0.12, hatMul: 1.2, densityMul: 0.7, kick: "floor", snare: "backbeat", bass: "eighths" },
  DUBSTEP: { swing: 0.2,  sidechain: 0.7, reverb: 0.22, hatMul: 0.8, densityMul: 0.6, kick: "half", snare: "half", bass: "sync" },
  NOISE:   { swing: 0.25, sidechain: 0.3, reverb: 0.16, hatMul: 1.3, densityMul: 1.1, kick: "euclid", snare: "euclid", bass: "dense" },
};

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => { a |= 0; a = (a + 0x6d2b79f5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
}
function hash(s: string): number { let h = 2166136261; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }
const clamp = (v: number, lo: number, hi: number): number => Math.min(hi, Math.max(lo, v));

function euclid(k: number, n: number, rot: number): boolean[] {
  const out = new Array(n).fill(false);
  if (k <= 0) return out; k = Math.min(k, n);
  let bucket = 0;
  for (let i = 0; i < n; i++) { bucket += k; if (bucket >= n) { bucket -= n; out[(i + rot) % n] = true; } }
  return out;
}
function steps(arr: number[]): boolean[] { const o = new Array(16).fill(false); for (const i of arr) o[i % 16] = true; return o; }

export interface Factors { engine: string; climate: string; current: string; soil: string; weather: string }
export interface SectionInfo { stage: number; section: number }

export class Arranger {
  stage = 1; section = 0;
  private lastSec = -1;

  update(cycle: number, state: ParamState, seq: BeatSequencer, f: Factors): SectionInfo | null {
    const sectionBars = Math.max(1, Math.round(state.sectionBars as number));
    const stageBars = Math.max(1, Math.round(state.stageBars as number));
    const sec = Math.floor(cycle / sectionBars);
    if (sec === this.lastSec) return null;
    this.lastSec = sec; this.section = sec;
    this.stage = 1 + (Math.floor(cycle / stageBars) % 5);
    this.derive(state, seq, f, sec, this.stage, state.character as string);
    return { stage: this.stage, section: sec };
  }

  private derive(state: ParamState, seq: BeatSequencer, f: Factors, sec: number, stage: number, genre: string): void {
    const rng = mulberry32(hash(`${genre}|${f.engine}|${f.climate}|${f.current}|${f.soil}|${f.weather}|${sec}`));
    const g = GENRE[genre] ?? GENRE.DUB;
    const energy = STAGE_E[stage];
    const cV = CLIMATE_V[f.climate], curV = CURRENT_V[f.current], soV = SOIL_V[f.soil], weV = WEATHER_V[f.weather];

    // global feel
    state.bpm = clamp(Math.round(84 + cV * 46 + energy * 14 + (rng() - 0.5) * 6), 40, 200);
    state.bassReso = clamp(Math.round(4 + soV * 12), 0, 25);
    state.swing = clamp(g.swing + weV * 0.12 + (f.engine === "PHYSICS" ? 0.1 * Math.sin(sec) : 0), 0, 0.7);
    state.sidechain = clamp(g.sidechain + energy * 0.15, 0, 1);
    state.reverbMix = clamp(g.reverb + weV * 0.2, 0, 1);
    state.patternDensity = clamp(0.25 + curV * 0.5, 0, 1);
    state.gateThresh = clamp(0.28 + (1 - energy) * 0.2, 0, 1);
    // gateMode is intentionally NOT auto-changed — the user's chosen gate stays fixed.
    state.bassCutoff = clamp(Math.round(500 + cV * 1400 + energy * 700), 100, 6000);

    const dens = (l: number): number => {
      let d = BASE[l] * (0.4 + energy) * g.densityMul;
      if (f.engine === "PHYSICS") d *= 0.5 + 0.5 * Math.sin(sec * 0.8 + l * 1.3 + curV * 6);
      if (f.engine === "PLANT") d *= 0.6 + 0.4 * (stage / 5);
      return clamp(d, 0, 0.95);
    };
    const kEu = (l: number): number => {
      let k = Math.round(dens(l) * 16);
      if (f.engine === "GEOMETRY") { const divs = [2, 4, 8, 16]; k = k <= 0 ? 0 : divs.reduce((a, b) => (Math.abs(b - k) < Math.abs(a - k) ? b : a)); }
      return k;
    };
    const rot = (l: number): number => f.engine === "GEOMETRY" ? (l * 2) % 8 : f.engine === "PLANT" ? (stage - 1 + l) % 4 : Math.floor(rng() * 16);

    // KICK
    seq.steps[K] = g.kick === "floor" ? steps(energy > 0.4 ? [0, 4, 8, 12] : [0, 8])
      : g.kick === "dubfloor" ? steps([0, 8])
      : g.kick === "half" ? steps([0, 11])
      : g.kick === "sparse" ? euclid(3, 16, 0)
      : euclid(kEu(K), 16, rot(K));
    // SNARE
    seq.steps[SN] = g.snare === "backbeat" ? steps([4, 12])
      : g.snare === "half" ? steps([8])
      : g.snare === "comp" ? euclid(4, 16, 2)
      : euclid(Math.max(3, kEu(SN)), 16, rot(SN));
    // HATS + others via euclid
    for (const l of [CL, HAT, OH, TOM, RIM, PERC]) {
      const mul = l === HAT || l === OH ? g.hatMul : 1;
      seq.steps[l] = euclid(Math.round(dens(l) * mul * 16), 16, rot(l));
    }
    // BASS
    seq.steps[BASS] = g.bass === "walk" ? euclid(9, 16, 0)
      : g.bass === "eighths" ? steps([0, 2, 4, 6, 8, 10, 12, 14])
      : g.bass === "sparse" ? euclid(3, 16, 2)
      : g.bass === "sync" ? euclid(5, 16, 2)
      : euclid(11, 16, Math.floor(rng() * 4)); // dense
    // probability shimmer
    for (let l = 0; l < 9; l++) { const pr = seq.prob[l]; for (let s = 0; s < 16; s++) pr[s] = 0.65 + rng() * 0.35; }
  }
}
